logging:
  level:
    de: TRACE
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
redisson:
  config: classpath:redisson.conf
